name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
      - uses: ilammy/setup-nasm@v1
      - uses: taiki-e/install-action@cargo-binstall
      - name: Install dioxus-cli
        run: cargo binstall -y dioxus-cli@0.7.0-alpha.3 --force --locked
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd example_projects
          $HOME/.cargo/bin/dx bundle --release --platform web
      - name: Copy index.html as 404.html for SPA routing
        run: |
          cp target/dx/docs/release/web/public/index.html target/dx/docs/release/web/public/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: target/dx/docs/release/web/public
          target-folder: docs
